name: Test 7 Repo

on:
  pull_request:
    branches: [ master, fixbugL6Painter ]
    paths-ignore:
      - '.github/workflows/**'
      - '**/mainTest.cpp'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: false
        default: 'staging'

jobs:
#   check_in_folder:
#     needs: get_changed_files
#     runs-on: ubuntu-latest
#     name: Check pattern
#     steps:
#     - name: Check pattern L1
#       if: ${{ contains(needs.get_changed_files.outputs.abc, 'AdvProg_L1-GuessIt') }}
#       run: |
#         echo "bingo contain ${{needs.get_changed_files.outputs.abc}}"
#     - name: Check L0
#       if: ${{ contains(needs.get_changed_files.outputs.abc, 'AdvProg_L0-Hello') }}
#       run: |
#         echo "bingo contain ${{needs.get_changed_files.outputs.abc}}"

  check_AdvProg_L0:
    runs-on: ubuntu-latest
    name: Check AdvProg_L0-Hello
    if: ${{ contains(needs.get_changed_files.outputs.abc, 'AdvProg_L0-Hello') }}
    steps:
      - uses: actions/checkout@v2
      - name: install package
        run: |
          sudo apt-get update
          sudo apt install -y libcppunit-dev
      - name: make & test
        working-directory: ./AdvProg_L0-Hello
        run: |
          chmod +x configure
          make
          make test

  # AdvProg_L1-GuessIt
  check_AdvProg_L1:
    runs-on: ubuntu-latest
    name: Check AdvProg_L1-GuessIt
    if: ${{ contains(needs.get_changed_files.outputs.abc, 'AdvProg_L1-GuessIt') }}
    steps:
      - uses: actions/checkout@v2
      - name: install package
        run: |
          sudo apt-get update
          sudo apt install -y libcppunit-dev
      - name: make & test
        working-directory: ./AdvProg_L1-GuessIt
        run: |
          chmod +x configure
          make
          make test

  # AdvProg_L2_Calculus
  check_AdvProg_L2:
    runs-on: ubuntu-latest
    name: Check AdvProg_L2-Calculus
    if: ${{ contains(needs.get_changed_files.outputs.abc, 'AdvProg_L2-Calculus') }}
    steps:
      - uses: actions/checkout@v2
      - name: install package
        run: |
          sudo apt-get update
          sudo apt install -y libcppunit-dev
      - name: make & test
        working-directory: ./AdvProg_L2-Calculus
        run: |
          chmod +x configure
          make
          make test

  # AdvProg_L3_HangMan
  check_AdvProg_L3:
    runs-on: ubuntu-latest
    name: Check AdvProg_L3-HangMan
    if: ${{ contains(needs.get_changed_files.outputs.abc, 'AdvProg_L3-HangMan') }}
    steps:
      - uses: actions/checkout@v2
      - name: install package
        run: |
          sudo apt-get update
          sudo apt install -y libcppunit-dev
      - name: make & test
        working-directory: ./AdvProg_L3-HangMan
        run: |
          chmod +x configure
          make
          make test

  # AdvProg_L4-SimpleAI
  check_AdvProg_L4:
    runs-on: ubuntu-latest
    name: Check AdvProg_L4-SimpleAI
    if: ${{ contains(needs.get_changed_files.outputs.abc, 'AdvProg_L4-SimpleAI') }}
    steps:
      - uses: actions/checkout@v2
      - name: install package
        run: |
          sudo apt-get update
          sudo apt install -y libcppunit-dev
      - name: make & test
        working-directory: ./AdvProg_L4-SimpleAI
        run: |
          chmod +x configure
          make
          make test

  # AdvProg_L5_Assessment
  check_AdvProg_L5:
    runs-on: ubuntu-latest
    name: Check AdvProg_L5-Assessment
    if: ${{ contains(needs.get_changed_files.outputs.abc, 'AdvProg_L5-Assessment') }}
    steps:
      - uses: actions/checkout@v2
      - name: install package
        run: |
          sudo apt-get update
          sudo apt install -y libcppunit-dev
      - name: make & test
        working-directory: ./AdvProg_L5-Assessment
        run: |
          chmod +x configure
          make
          make test

  # AdvProg_L6-Painter
  check_AdvProg_L6:
    runs-on: ubuntu-latest
    name: Check AdvProg_L6-Painter
    if: ${{ contains(needs.get_changed_files.outputs.abc, 'AdvProg_L6-Painter') }}
    steps:
      - uses: actions/checkout@v2
      - name: install package
        run: |
          sudo apt-get update
          sudo apt install -y libcppunit-dev
          sudo apt install libsdl2-dev
          sudo apt install libsdl2-image-dev
      - name: make & test
        working-directory: ./AdvProg_L6-Painter
        run: |
          chmod +x configure
          make
          make test

  # AdvProg_L7-Snake
  check_AdvProg_L7:
    runs-on: ubuntu-latest
    name: Check AdvProg_L7-Snake
    if: ${{ contains(needs.get_changed_files.outputs.abc, 'AdvProg_L7-Snake') }}
    steps:
      - uses: actions/checkout@v2
      - name: install package
        run: |
          sudo apt-get update
          sudo apt install -y libcppunit-dev
          sudo apt install libsdl2-dev
          sudo apt install libsdl2-image-dev
      - name: make & test
        working-directory: ./AdvProg_L7-Snake
        run: |
          chmod +x configure
          ./configure
          make
          make test
